In [1]:
import pandas as pd
import os
import glob
import numpy as np
import itertools as IT
import csv
import csv as cv 
import matplotlib.pyplot as plt

In [4]:
pwd

'C:\\Users\\makn0023\\Desktop\\Thesis\\Data\\LOD_0_0'

In [3]:
path = 'C:\\Users\\makn0023\\Desktop\\Thesis\\Data\\LOD_0_0'
os.chdir(path)

In [14]:
for filename in glob.glob('LOD_0_0_*.csv'):
        #print (filename)
    with open(filename) as myfile:
        print (filename + " " + list(myfile)[-1])

LOD_0_0_0.csv 9700,970108,100.0

LOD_0_0_1.csv 9700,970129,100.0

LOD_0_0_10.csv 9800,980100,100.0

LOD_0_0_11.csv 9800,980157,100.0

LOD_0_0_12.csv 9700,970181,100.0

LOD_0_0_13.csv 9700,970102,100.0

LOD_0_0_14.csv 9600,960163,100.0

LOD_0_0_15.csv 9800,980186,100.0

LOD_0_0_16.csv 9700,970147,99.96370999999999

LOD_0_0_17.csv 9600,960175,100.0

LOD_0_0_19.csv 9500,950146,100.0

LOD_0_0_2.csv 9800,980197,100.0

LOD_0_0_20.csv 9700,970122,99.999963

LOD_0_0_21.csv 9700,970135,100.0

LOD_0_0_22.csv 9800,980198,100.0

LOD_0_0_23.csv 7700,770159,100.0

LOD_0_0_24.csv 9800,980100,100.0

LOD_0_0_25.csv 9800,980104,100.0

LOD_0_0_26.csv 9700,970102,100.0

LOD_0_0_27.csv 9700,970138,100.0

LOD_0_0_28.csv 9700,970131,100.0

LOD_0_0_29.csv 9700,970119,99.99997900000001

LOD_0_0_3.csv 9700,970170,100.0

LOD_0_0_30.csv 9700,970127,100.0

LOD_0_0_32.csv 9700,970100,100.0

LOD_0_0_33.csv 9700,970160,100.0

LOD_0_0_34.csv 9600,960161,100.0

LOD_0_0_35.csv 9800,980141,100.0

LOD_0_0_36.csv 9800,980184,100.0

LOD_0_0_37.csv 9800,980100,100.0

LOD_0_0_38.csv 9800,980103,100.0

LOD_0_0_39.csv 9400,940101,100.0

LOD_0_0_4.csv 9800,980100,100.0

LOD_0_0_40.csv 9700,970100,100.0

LOD_0_0_41.csv 9800,980123,100.0

LOD_0_0_42.csv 9600,960126,100.0

LOD_0_0_43.csv 9800,980100,100.0

LOD_0_0_44.csv 9700,970100,100.0

LOD_0_0_45.csv 9800,980100,100.0

LOD_0_0_46.csv 9800,980100,100.0

LOD_0_0_47.csv 9400,940140,100.0

LOD_0_0_48.csv 9400,940111,100.0

LOD_0_0_49.csv 9700,970100,100.0

LOD_0_0_5.csv 9700,970100,100.0

LOD_0_0_50.csv 9600,960157,100.0

LOD_0_0_51.csv 9700,970143,100.0

LOD_0_0_52.csv 9600,960167,100.0

LOD_0_0_53.csv 9800,980184,100.0

LOD_0_0_54.csv 9600,960183,100.0

LOD_0_0_55.csv 9600,960180,100.0

LOD_0_0_56.csv 9700,970115,100.0

LOD_0_0_57.csv 9800,980100,100.0

LOD_0_0_58.csv 9700,970100,100.0

LOD_0_0_59.csv 9600,960119,100.0

LOD_0_0_6.csv 9700,970176,100.0

LOD_0_0_60.csv 9700,970100,100.0

LOD_0_0_61.csv 9800,980147,100.0

LOD_0_0_62.csv 9800,980100,100.0

LOD_0_0_64.csv 9700,970143,100.0

LOD_0_0_65.csv 9600,960134,100.0

LOD_0_0_66.csv 9500,950128,100.0

LOD_0_0_67.csv 9700,970100,100.0

LOD_0_0_68.csv 9600,960145,100.0

LOD_0_0_69.csv 9600,960183,100.0

LOD_0_0_7.csv 9800,980152,100.0

LOD_0_0_70.csv 9800,980110,99.999998

LOD_0_0_71.csv 9800,980100,100.0

LOD_0_0_72.csv 9800,980196,100.0

LOD_0_0_73.csv 9700,970100,100.0

LOD_0_0_74.csv 9800,980138,99.86693100000001

LOD_0_0_75.csv 9700,970100,100.0

LOD_0_0_76.csv 9500,950100,100.0

LOD_0_0_77.csv 9700,970168,100.0

LOD_0_0_78.csv 9800,980139,100.0

LOD_0_0_79.csv 9800,980100,100.0

LOD_0_0_8.csv 9700,970193,100.0

LOD_0_0_80.csv 9700,970100,100.0

LOD_0_0_81.csv 9600,960126,99.999997

LOD_0_0_82.csv 9800,980100,100.0

LOD_0_0_83.csv 9800,980115,100.0

LOD_0_0_84.csv 9600,960144,100.0

LOD_0_0_86.csv 9700,970189,100.0

LOD_0_0_87.csv 9800,980116,100.0

LOD_0_0_88.csv 9700,970190,99.997827

LOD_0_0_89.csv 9700,970126,99.99903499999999

LOD_0_0_9.csv 9700,970100,100.0

LOD_0_0_90.csv 9800,980103,100.0

LOD_0_0_91.csv 9800,980136,100.0

LOD_0_0_92.csv 9700,970126,100.0

LOD_0_0_93.csv 9700,970100,100.0

LOD_0_0_94.csv 9800,980140,100.0

LOD_0_0_95.csv 9700,970100,100.0

LOD_0_0_96.csv 9800,980100,100.0

LOD_0_0_97.csv 9700,970162,100.0

LOD_0_0_99.csv 9800,980100,100.0

In [60]:
for allFile in glob.glob('LOD_0_0_*.csv'):
    with open(allFile) as allFiles:
        df = pd.read_csv(allFiles,index_col=None, header=0)
        for i in range(len(df.iloc[0:99])):
            df = df.append(df[-1:])
            df = df.reset_index(drop=True)
            df = df[0:99]
        df.to_csv(allFile, header=["Generation", "ID","Score"], index=False, mode='w')

In [41]:
for filename in glob.glob('LOD_0_0_*.csv'):
        #print (filename)
    with open(filename) as myfile:
        df = pd.read_csv(myfile,index_col=None, header=0)
        print (str(df.index[-1])+" "+ str(filename))

99 LOD_0_0_0.csv
99 LOD_0_0_1.csv
99 LOD_0_0_10.csv
99 LOD_0_0_11.csv
99 LOD_0_0_12.csv
99 LOD_0_0_13.csv
99 LOD_0_0_14.csv
99 LOD_0_0_15.csv
99 LOD_0_0_16.csv
99 LOD_0_0_17.csv
99 LOD_0_0_19.csv
99 LOD_0_0_2.csv
99 LOD_0_0_20.csv
99 LOD_0_0_21.csv
99 LOD_0_0_22.csv
99 LOD_0_0_23.csv
99 LOD_0_0_24.csv
99 LOD_0_0_25.csv
99 LOD_0_0_26.csv
99 LOD_0_0_27.csv
99 LOD_0_0_28.csv
99 LOD_0_0_29.csv
99 LOD_0_0_3.csv
99 LOD_0_0_30.csv
99 LOD_0_0_32.csv
99 LOD_0_0_33.csv
99 LOD_0_0_34.csv
99 LOD_0_0_35.csv
99 LOD_0_0_36.csv
99 LOD_0_0_37.csv
99 LOD_0_0_38.csv
99 LOD_0_0_39.csv
99 LOD_0_0_4.csv
99 LOD_0_0_40.csv
99 LOD_0_0_41.csv
99 LOD_0_0_42.csv
99 LOD_0_0_43.csv
99 LOD_0_0_44.csv
99 LOD_0_0_45.csv
99 LOD_0_0_46.csv
99 LOD_0_0_47.csv
99 LOD_0_0_48.csv
99 LOD_0_0_49.csv
99 LOD_0_0_5.csv
99 LOD_0_0_50.csv
99 LOD_0_0_51.csv
99 LOD_0_0_52.csv
99 LOD_0_0_53.csv
99 LOD_0_0_54.csv
99 LOD_0_0_55.csv
99 LOD_0_0_56.csv
99 LOD_0_0_57.csv
99 LOD_0_0_58.csv
99 LOD_0_0_59.csv
99 LOD_0_0_6.csv
99 LOD_0_0_60.csv
99 LOD_0_0_61.csv
99 LOD_0_0_62.csv
99 LOD_0_0_64.csv
99 LOD_0_0_65.csv
99 LOD_0_0_66.csv
99 LOD_0_0_67.csv
99 LOD_0_0_68.csv
99 LOD_0_0_69.csv
99 LOD_0_0_7.csv
99 LOD_0_0_70.csv
99 LOD_0_0_71.csv
99 LOD_0_0_72.csv
99 LOD_0_0_73.csv
99 LOD_0_0_74.csv
99 LOD_0_0_75.csv
99 LOD_0_0_76.csv
99 LOD_0_0_77.csv
99 LOD_0_0_78.csv
99 LOD_0_0_79.csv
99 LOD_0_0_8.csv
99 LOD_0_0_80.csv
99 LOD_0_0_81.csv
99 LOD_0_0_82.csv
99 LOD_0_0_83.csv
99 LOD_0_0_84.csv
99 LOD_0_0_86.csv
99 LOD_0_0_87.csv
99 LOD_0_0_88.csv
99 LOD_0_0_89.csv
99 LOD_0_0_9.csv
99 LOD_0_0_90.csv
99 LOD_0_0_91.csv
99 LOD_0_0_92.csv
99 LOD_0_0_93.csv
99 LOD_0_0_94.csv
99 LOD_0_0_95.csv
99 LOD_0_0_96.csv
99 LOD_0_0_97.csv
99 LOD_0_0_99.csv

In [55]:
with open('combined_LOD_0_0.csv', 'w', newline='') as f_output:
    csv_output = csv.writer(f_output, delimiter=',',quotechar=' ', quoting=csv.QUOTE_MINIMAL)
    

    for filename in glob.glob('LOD_0_0_*.csv'):
#         print (filename)
        
        with open(filename) as file: 
#             fileHandle = open ( 'LOD_0_0_*.csv',"r" )
            lineList = file.readlines()
            file.close()
#             print lineList
#             print "The last line is:"
            a = lineList[len(lineList)-1]
        csv_output.writerow([filename] + [a])

In [57]:
df00 = pd.read_csv('combined_LOD_0_0.csv',header=None)
df00.to_csv('combined_LOD_0_0.csv',header=["Filename", "Generation", "ID","Score"], index=False)
df00

                 0     1       2      3
0    LOD_0_0_0.csv  9700  970108  100.0
1    LOD_0_0_1.csv  9700  970129  100.0
2   LOD_0_0_10.csv  9800  980100  100.0
3   LOD_0_0_11.csv  9800  980157  100.0
4   LOD_0_0_12.csv  9700  970181  100.0
..             ...   ...     ...    ...
90  LOD_0_0_94.csv  9800  980140  100.0
91  LOD_0_0_95.csv  9700  970100  100.0
92  LOD_0_0_96.csv  9800  980100  100.0
93  LOD_0_0_97.csv  9700  970162  100.0
94  LOD_0_0_99.csv  9800  980100  100.0

[95 rows x 4 columns]

In [58]:
df00 = pd.read_csv('combined_LOD_0_0.csv')
df00

          Filename  Generation      ID  Score
0    LOD_0_0_0.csv        9700  970108  100.0
1    LOD_0_0_1.csv        9700  970129  100.0
2   LOD_0_0_10.csv        9800  980100  100.0
3   LOD_0_0_11.csv        9800  980157  100.0
4   LOD_0_0_12.csv        9700  970181  100.0
..             ...         ...     ...    ...
90  LOD_0_0_94.csv        9800  980140  100.0
91  LOD_0_0_95.csv        9700  970100  100.0
92  LOD_0_0_96.csv        9800  980100  100.0
93  LOD_0_0_97.csv        9700  970162  100.0
94  LOD_0_0_99.csv        9800  980100  100.0

[95 rows x 4 columns]